# Generated by Django 5.0.3 on 2024-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_menu_price_purchase_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_price',
            field=models.FloatField(),
        ),
    ]
