# Generated by Django 5.0.3 on 2024-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menuitem_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
