# Generated by Django 5.0.3 on 2024-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_purchase_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('ingredient_amount', models.FloatField(default=0)),
                ('ingredient_unit', models.CharField(choices=[('Liter', 'l'), ('Gramm', 'g'), ('Kilogramm', 'kg'), ('Milliliter', 'ml')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
