# Generated by Django 5.0.3 on 2024-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_ingredient_delete_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_ingredients',
            field=models.JSONField(default=0, null=True),
        ),
    ]
