# Generated by Django 5.0.3 on 2024-04-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menuitem_menu_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_unit',
            field=models.CharField(choices=[('g', 'g')], max_length=30),
        ),
    ]
