# Generated by Django 5.0.3 on 2024-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_ingredient_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_unit',
            field=models.CharField(choices=[('g', 'Gramm')], max_length=30),
        ),
    ]
