# Generated by Django 5.0.3 on 2024-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_ingredient_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_per_kilo',
            field=models.FloatField(default=0, null=True),
        ),
    ]
