# Generated by Django 5.0.3 on 2024-04-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_rename_item_price_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pre_delete_item_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem'),
        ),
    ]
