# Generated by Django 5.0.3 on 2024-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_purchase_pre_delete_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
